module.exports = {
	CLIENT_ID: '890901164781101106',
	PLAY_LIVE_STREAM: '',
	PLAY_VIDEO_LONGER_THAN_1_HOUR: '',
	MAX_QUEUE_LENGTH: '',
	AUTO_SHUFFLE_YOUTUBE_PLAYLIST: '',
	LEAVE_TIMEOUT: '',
	MAX_RESPONSE_TIME: '',
	DELETE_OLD_PLAY_MESSAGE: '',
};